Config:
    #API endpoint URL, required
    api-url: {apiURL}
    #API token string, required
    token: {token}
    #submission ID, required
    submission: {submissionID}
    #upload type,  valid value in [data file, metadata], required
    type: data file
    #folder that contains either data files (type = file) or metadata (TSV/TXT) files (type = metadata), required
    data: {dataFolder}
    #path to manifest file, conditional required when type = file
    manifest: {manifest}
     # path to archive manifest file, conditional required when uploading any zipped (.zip) data files.
    archive_manifest: {archive_manifest}
    #file uploading retries
    retries: 3
    # if overwrite existed file
    overwrite: false
    # if only run file validation without uploading
    dryrun: false